/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bemach_examples_jni_SayHelloJni */

#ifndef _Included_com_bemach_examples_jni_SayHelloJni
#define _Included_com_bemach_examples_jni_SayHelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bemach_examples_jni_SayHelloJni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bemach_examples_jni_SayHelloJni_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
